CREATE TABLE IF NOT EXISTS products(
    id SERIAL PRIMARY KEY,
    pname VARCHAR(255) NOT NULL,
    price NUMERIC NOT NULL DEFAULT 0,
    category VARCHAR(255) NOT NULL DEFAULT 'General',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);